# Generated by Django 5.0.2 on 2024-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('emotes', models.JSONField(default=dict)),
                ('files', models.FileField(blank=True, null=True, upload_to='channel_messages/')),
            ],
        ),
    ]
