# Generated by Django 5.0.2 on 2024-02-17 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direct_message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directchat',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directchatthread',
            name='direct_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='direct_message.directchat'),
        ),
        migrations.AddField(
            model_name='directchatthreadmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_chat_thread_messages', to='direct_message.directchatthread'),
        ),
        migrations.AddField(
            model_name='directmessages',
            name='directChat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='direct_message.directchat'),
        ),
    ]
