# Generated by Django 5.0.2 on 2024-02-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
