# Generated by Django 5.0.2 on 2024-02-23 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_channel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
